export default {

    
    LOGIN : "LOGIN" , 
    ON_LOGOUT : "ON_LOGOUT",
    ISLOGIN : "ISLOGIN",
    OTP_VERIFY :"OTP_VERIFY",
    ADD_TO_CART:"ADD_TO_CART",
    DELETE_FROM_CART:"DELETE_FROM_CART",
    INCREMENT_CART:"INCREMENT_CART",
    DECREMENT_CART:"DECREMENT_CART"
    
    
}